name: Build and Release VSCode Extension

on:
  push:
    tags:
      - "v*.*.*" # v1.2.3 형식의 태그에서만 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install vsce
        run: npm install -g @vscode/vsce

      - name: Update package.json version
        run: |
          TAG=${GITHUB_REF#refs/tags/}
          VERSION=${TAG#v}
          echo "Version from tag: $VERSION"
          npm version $VERSION --no-git-tag-version

      - name: Package extension
        run: vsce package

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: "*.vsix"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
